name: Create Release

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  create_release:
    runs-on:
      group: Default

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'
      env:
        DOTNET_INSTALL_DIR: ~/.dotnet

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3.1.11
      with:
        versionSpec: '6.0.x'

    - name: Run gitversion
      uses: gittools/actions/gitversion/execute@v3.0.0
      id: gitversion

    - name: Install github-cli
      run: sudo apt update && sudo apt install -y gh --no-install-recommends

    - name: Create release
      run: |
        set -e
        gh release create "${{ steps.gitversion.outputs.fullSemVer }}" -t "${{ steps.gitversion.outputs.fullSemVer }}" --generate-notes
        git push origin --tags
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        INPUT_TAG: ${{ steps.gitversion.outputs.tag }}

    - name: Docker login to Quay
      uses: docker/login-action@v3
      with:
        registry: ${{ vars.REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
 
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        # list of Docker images to use as base name for tags
        images: |
          ${{ vars.REGISTRY }}/${{ vars.IMAGE_NAME }}
        # generate Docker tags based on the following events/attributes
        tags: |
          type=semver,pattern={{raw}},value=${{ steps.gitversion.outputs.fullSemVer }}
          type=semver,pattern={{major}}.{{minor}},value=${{steps.gitversion.outputs.fullSemVer}},enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
          type=semver,pattern={{major}},value=${{steps.gitversion.outputs.fullSemVer}},enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
          type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
